const CORE_WORDS = [
  'rain',
  'storm',
  'typing',
  'neon',
  'shadow',
  'window',
  'street',
  'signal',
  'rocket',
  'glimmer',
  'memory',
  'thread',
  'rhythm',
  'moment',
  'focus',
  'vector',
  'ripple',
  'cascade',
  'anchor',
  'current',
  'charge',
  'static',
  'silver',
  'carbon',
  'ember',
  'echo',
  'flare',
  'lumen',
  'socket',
  'cipher',
  'matrix',
  'binary',
  'vertex',
  'quantum',
  'clock',
  'horizon',
  'tempo',
  'velocity',
  'pulse',
  'signal',
  'gloss',
  'bridge',
  'planet',
  'mercury',
  'saturn',
  'galaxy',
  'jupiter',
  'comet',
  'meteor',
  'planet',
  'future',
  'urban',
  'alley',
  'district',
  'engine',
  'device',
  'module',
  'portal',
  'dynamic',
  'method',
  'factor',
  'status',
  'module',
  'syntax',
  'shader',
  'render',
  'canvas',
  'kernel',
  'packet',
  'stream',
  'target',
  'vector',
  'ranger',
  'walker',
  'breaker',
  'mirror',
  'frozen',
  'copper',
  'magnet',
  'harbor',
  'lamps',
  'mosaic',
  'harvest',
  'thunder',
  'raindrop',
  'letter',
  'forest',
  'winter',
  'summer',
  'autumn',
  'spring',
  'breeze',
  'gust',
  'cloud',
  'vapor',
  'glacier',
  'ocean',
  'delta',
  'coast',
  'harvest',
  'meadow',
  'lighthouse',
  'arcade',
  'circuit',
  'satellite',
  'project',
  'monitor',
  'insight',
  'uplink',
  'network',
  'forecast',
  'drizzle',
  'downpour',
  'fountain',
  'meridian',
  'signaler',
  'postcard',
  'journey',
  'archive',
  'navigator',
  'lattice',
  'polar',
  'fusion',
  'nova',
  'stellar',
  'drifter',
  'voyager',
  'humming',
  'silence',
  'ceramic',
  'granite',
  'granular',
  'fabric',
  'canvas',
  'pixel',
  'outline',
  'origin',
  'planetary',
  'stormlight',
  'threshold',
  'waterline',
  'grounded',
  'lantern',
  'streetcar',
  'midnight',
  'railing',
  'smolder',
  'hollow',
  'silent',
  'kinetic',
  'upriver',
  'bottleneck',
  'downtown',
  'crosswind',
  'cathedral',
  'warehouse',
  'turnstile',
  'backlight',
  'riverstone',
  'semaphore',
  'luminance',
  'waterfront',
  'rainproof',
  'nightfall',
  'afterglow',
  'windward',
  'updraft',
  'starboard',
  'terminal',
  'framework',
  'operand',
  'runtime',
  'compile',
  'deltaflow',
  'streaming',
  'controller',
  'response',
  'payload',
  'snapshot',
  'glowline',
  'subtle',
  'elegant',
  'realism',
  'splash',
  'rivulet',
  'puddle',
  'spectrum',
  'density',
  'clarity',
  'precision',
  'balance',
  'momentum',
  'terrain',
  'polished',
  'gesture',
  'mechanic',
  'session',
  'record',
  'history',
  'timing',
  'average',
  'minimum',
  'maximum',
  'quality',
  'setting',
  'profile',
  'trigger',
  'camera',
  'layer',
  'forefront',
  'backdrop',
  'vignette',
  'ambient',
  'reflect',
  'shimmer',
  'nocturne',
  'crosswalk',
  'traffic',
  'avenue',
  'districts',
  'aluminum',
  'warehouse',
  'generator',
  'operator',
  'cobblestone',
  'quicksilver',
  'frequency',
  'transient',
  'infinite',
  'boundary',
  'northern',
  'southern',
  'eastern',
  'western',
  'junction',
  'assembly',
  'artifact',
  'fidelity',
  'gradient',
  'harmonic',
  'resonance',
  'overcast',
  'rainfall',
  'drifting',
  'lively',
  'threshold',
  'airborne',
  'soundscape',
  'luminous',
  'dispatch',
  'firewatch',
  'watchtower',
  'dockyard',
  'boardwalk',
  'shoreline',
  'synergy',
  'workflow',
  'signalpath',
  'telemetry',
  'interface',
  'overlay',
  'keyframe',
  'compositor',
  'persistence',
  'database',
  'transaction',
  'rollback',
  'migration',
  'cursor',
  'surface',
  'hologram',
  'moonlit',
  'riverbank',
  'undertow',
  'stability',
  'immersive',
  'playfield',
];

const PREFIXES = [
  'ra', 'ne', 'cy', 'lu', 'br', 'st', 'mo', 'di', 'ca', 'tr', 'fl', 'sp', 'gl', 'sh', 'cl',
  'wi', 'th', 'pr', 'ch', 'fr', 'bl', 'gr', 'vo', 'qu', 'ha', 'me', 'co', 'po', 'si', 'ni',
];

const ROOTS = [
  'nex', 'rift', 'line', 'drop', 'shade', 'light', 'trace', 'pulse', 'frame', 'crest',
  'stream', 'point', 'stone', 'field', 'gale', 'flux', 'spark', 'clock', 'grid', 'shore',
  'drift', 'wave', 'forge', 'scope', 'rail', 'plane', 'mark', 'phase', 'tide', 'crest',
];

const SUFFIXES = [
  'er', 'ing', 'ed', 'ion', 'al', 'ory', 'ance', 'ist', 'ive', 'ure', 'ent', 'oid',
];

function buildWordList(): string[] {
  const words = new Set<string>(CORE_WORDS.map((word) => word.toLowerCase()));

  for (const prefix of PREFIXES) {
    for (const root of ROOTS) {
      words.add((prefix + root).toLowerCase());
      for (const suffix of SUFFIXES) {
        words.add((prefix + root + suffix).toLowerCase());
      }
    }
  }

  const cleaned = [...words].filter(
    (word) => word.length >= 3 && word.length <= 12 && /^[a-z]+$/.test(word),
  );

  cleaned.sort();
  const trimmed = cleaned.slice(0, 3200);

  if (trimmed.length < 2000) {
    throw new Error('Word list generation produced fewer than 2000 words.');
  }

  return trimmed;
}

export const WORD_LIST = buildWordList();
