import type { FingerId } from './keyboardLayout';

export type LessonStep =
  | { kind: 'intro_key'; key: string; finger: FingerId; description: string }
  | { kind: 'drill'; prompt: string; hint?: string }
  | { kind: 'word_drill'; words: string[]; hint?: string }
  | { kind: 'practice'; durationSeconds: number; pool: string[] };

export interface Lesson {
  id: string;
  unit: string;
  order: number;
  title: string;
  summary: string;
  steps: LessonStep[];
  unlockRequires?: string;
}

// ---- helpers ----
function intro(key: string, finger: FingerId, description: string): LessonStep {
  return { kind: 'intro_key', key, finger, description };
}
function drill(prompt: string, hint?: string): LessonStep {
  return { kind: 'drill', prompt, hint };
}
function words(list: string[], hint?: string): LessonStep {
  return { kind: 'word_drill', words: list, hint };
}
function practice(pool: string[], durationSeconds = 60): LessonStep {
  return { kind: 'practice', durationSeconds, pool };
}

interface Builder {
  id: string;
  title: string;
  summary: string;
  steps: LessonStep[];
}

function buildUnit(unit: string, builders: Builder[], startOrder: number): Lesson[] {
  const result: Lesson[] = [];
  let prev: string | undefined;
  builders.forEach((b, i) => {
    result.push({
      id: b.id,
      unit,
      order: startOrder + i,
      title: b.title,
      summary: b.summary,
      steps: b.steps,
      unlockRequires: prev,
    });
    prev = b.id;
  });
  return result;
}

// ---- Unit 1: Home Row ----
const homeRow: Builder[] = [
  {
    id: 'hr.01.f',
    title: 'Key: F',
    summary: 'Left index home key — anchor finger.',
    steps: [
      intro('f', 'L_INDEX', 'Rest your left index finger on F — feel the bump.'),
      drill('f f f f f f f f f f'),
      drill('fff fff fff fff fff'),
      drill('ffff ffff ffff ffff'),
      drill('ff f ff f ff f ff f ff'),
    ],
  },
  {
    id: 'hr.02.j',
    title: 'Key: J',
    summary: 'Right index home key — anchor finger.',
    steps: [
      intro('j', 'R_INDEX', 'Rest your right index finger on J — feel the bump.'),
      drill('j j j j j j j j j j'),
      drill('jjj jjj jjj jjj jjj'),
      drill('jjjj jjjj jjjj jjjj'),
      drill('jj j jj j jj j jj j jj'),
    ],
  },
  {
    id: 'hr.03.fj',
    title: 'F & J',
    summary: 'Alternate index fingers across the gap.',
    steps: [
      drill('fj fj fj fj fj fj fj fj'),
      drill('fjf jfj fjf jfj fjf jfj'),
      drill('fff jjj fff jjj fff jjj'),
      drill('fjfj jfjf fjfj jfjf fjfj'),
      drill('ffjj jjff ffjj jjff ffjj'),
    ],
  },
  {
    id: 'hr.04.d',
    title: 'Key: D',
    summary: 'Left middle home key.',
    steps: [
      intro('d', 'L_MIDDLE', 'Left middle finger rests on D, right next to F.'),
      drill('d d d d d d d d d d'),
      drill('ddd ddd ddd ddd ddd'),
      drill('dfd dfd dfd dfd dfd'),
      drill('dd df fd dd df fd dd'),
    ],
  },
  {
    id: 'hr.05.k',
    title: 'Key: K',
    summary: 'Right middle home key.',
    steps: [
      intro('k', 'R_MIDDLE', 'Right middle finger rests on K, right next to J.'),
      drill('k k k k k k k k k k'),
      drill('kkk kkk kkk kkk kkk'),
      drill('kjk kjk kjk kjk kjk'),
      drill('kk kj jk kk kj jk kk'),
    ],
  },
  {
    id: 'hr.06.dk',
    title: 'D & K',
    summary: 'Middle fingers and their index neighbors.',
    steps: [
      drill('dk dk dk dk dk dk dk dk'),
      drill('dkd kdk dkd kdk dkd kdk'),
      drill('fdk jkf fdk jkf fdk jkf'),
      drill('dfjk kjfd dfjk kjfd dfjk'),
      drill('ddkk kkdd ddkk kkdd ddkk'),
    ],
  },
  {
    id: 'hr.07.mix1',
    title: 'Mix: F J D K',
    summary: 'All four inner home keys combined.',
    steps: [
      drill('fjdk fjdk fjdk fjdk fjdk'),
      drill('fd jk fd jk fd jk fd jk'),
      drill('dfjk kjfd fjdk dkfj dfjk'),
      drill('fjfj dkdk fjfj dkdk fjfj'),
      drill('fkdj jdkf fkdj jdkf fkdj'),
    ],
  },
  {
    id: 'hr.08.test1',
    title: 'Test: Center Keys',
    summary: 'Speed test on F J D K.',
    steps: [
      practice(
        [
          'fj',
          'dk',
          'fd',
          'jk',
          'fk',
          'dj',
          'fjdk',
          'kjfd',
          'dkfj',
          'jdkf',
          'fdjk',
          'kjdf',
          'ffjj',
          'ddkk',
          'fjfj',
          'dkdk',
          'fkdj',
          'jdkf',
          'djfk',
          'kfjd',
        ],
        75,
      ),
    ],
  },
  {
    id: 'hr.09.s',
    title: 'Key: S',
    summary: 'Left ring home key.',
    steps: [
      intro('s', 'L_RING', 'Left ring finger rests on S, next to D.'),
      drill('s s s s s s s s s s'),
      drill('sss sss sss sss sss'),
      drill('sds sds sds sds sds'),
      drill('sdf sdf sdf sdf sdf'),
    ],
  },
  {
    id: 'hr.10.l',
    title: 'Key: L',
    summary: 'Right ring home key.',
    steps: [
      intro('l', 'R_RING', 'Right ring finger rests on L, next to K.'),
      drill('l l l l l l l l l l'),
      drill('lll lll lll lll lll'),
      drill('lkl lkl lkl lkl lkl'),
      drill('lkj lkj lkj lkj lkj'),
    ],
  },
  {
    id: 'hr.11.sl',
    title: 'S & L',
    summary: 'Ring fingers reach across the row.',
    steps: [
      drill('sl sl sl sl sl sl sl sl'),
      drill('sls lsl sls lsl sls lsl'),
      drill('sdf jkl sdf jkl sdf jkl'),
      drill('sldk fdks lksd fdks sldk'),
      drill('ssll llss ssll llss ssll'),
    ],
  },
  {
    id: 'hr.12.a',
    title: 'Key: A',
    summary: 'Left pinky home key.',
    steps: [
      intro('a', 'L_PINKY', 'Left pinky rests on A, at the far left of home row.'),
      drill('a a a a a a a a a a'),
      drill('aaa aaa aaa aaa aaa'),
      drill('asa asa asa asa asa'),
      drill('asdf asdf asdf asdf'),
    ],
  },
  {
    id: 'hr.13.semi',
    title: 'Key: ;',
    summary: 'Right pinky home key.',
    steps: [
      intro(';', 'R_PINKY', 'Right pinky rests on the semicolon, at the far right of home row.'),
      drill('; ; ; ; ; ; ; ; ; ;'),
      drill(';;; ;;; ;;; ;;; ;;;'),
      drill(';l; ;l; ;l; ;l; ;l;'),
      drill(';lkj ;lkj ;lkj ;lkj'),
    ],
  },
  {
    id: 'hr.14.asemi',
    title: 'A & ;',
    summary: 'Pinkies reach the row edges.',
    steps: [
      drill('a; a; a; a; a; a; a; a;'),
      drill('a;a ;a; a;a ;a; a;a ;a;'),
      drill('asdf jkl; asdf jkl; asdf'),
      drill('a;s;d;f; j;k;l; a;s;d;f;'),
      drill('aa;; ;;aa aa;; ;;aa aa;;'),
    ],
  },
  {
    id: 'hr.15.test2',
    title: 'Test: Home Row Edges',
    summary: 'Speed test with all 8 home-row keys (no G, H yet).',
    steps: [
      practice(
        [
          'asdf',
          'jkl;',
          'sad',
          'lad',
          'dad',
          'ask',
          'flask',
          'salad',
          'dads',
          'fads',
          'asks',
          'lads',
          'adds',
          'alas',
          'fall',
          'all',
          'jaks',
          'lass',
          'asdf',
          'jkl;',
          'dfjk',
          'slak',
          'a;sl',
          'kdjf',
        ],
        75,
      ),
    ],
  },
  {
    id: 'hr.16.g',
    title: 'Key: G',
    summary: 'Left index stretches inward to G.',
    steps: [
      intro('g', 'L_INDEX', 'Stretch your left index finger right from F to G, then back.'),
      drill('g g g g g g g g g g'),
      drill('ggg ggg ggg ggg ggg'),
      drill('fgf fgf fgf fgf fgf'),
      drill('fgfg gfgf fgfg gfgf fgfg'),
    ],
  },
  {
    id: 'hr.17.h',
    title: 'Key: H',
    summary: 'Right index stretches inward to H.',
    steps: [
      intro('h', 'R_INDEX', 'Stretch your right index finger left from J to H, then back.'),
      drill('h h h h h h h h h h'),
      drill('hhh hhh hhh hhh hhh'),
      drill('jhj jhj jhj jhj jhj'),
      drill('jhjh hjhj jhjh hjhj jhjh'),
    ],
  },
  {
    id: 'hr.18.gh',
    title: 'G & H',
    summary: 'Index stretches meet in the middle.',
    steps: [
      drill('gh gh gh gh gh gh gh gh'),
      drill('ghg hgh ghg hgh ghg hgh'),
      drill('fgh jhg fgh jhg fgh jhg'),
      drill('fgf jhj fgf jhj fgf jhj'),
      drill('ggh hhg ggh hhg ggh hhg'),
    ],
  },
  {
    id: 'hr.19.full',
    title: 'Full Home Row',
    summary: 'All home row keys mixed together.',
    steps: [
      drill('asdfg hjkl; asdfg hjkl; asdfg'),
      drill(';lkjh gfdsa ;lkjh gfdsa ;lkjh'),
      drill('ask dad lad fall gall hall lash'),
      drill('glad fads jak has ash sal flask'),
      drill('aha gal haul salad flask shall'),
    ],
  },
  {
    id: 'hr.20.words',
    title: 'Home Row Words',
    summary: 'Real words built from the home row.',
    steps: [
      words([
        'fall',
        'all',
        'ask',
        'has',
        'had',
        'glad',
        'lash',
        'gal',
        'dad',
        'hall',
        'flask',
        'salad',
        'haul',
        'gash',
        'dash',
        'sash',
        'alas',
        'lass',
        'shall',
        'slag',
        'flag',
        'half',
        'alfalfa',
        'jak',
      ]),
    ],
  },
  {
    id: 'hr.21.test3',
    title: 'Test: Home Row Mastery',
    summary: 'Timed home-row mastery run.',
    steps: [
      practice(
        [
          'fall',
          'all',
          'ask',
          'has',
          'had',
          'glad',
          'lash',
          'gal',
          'dad',
          'hall',
          'flask',
          'salad',
          'haul',
          'gash',
          'dash',
          'sash',
          'alas',
          'lass',
          'shall',
          'slag',
          'flag',
          'half',
          'gaff',
          'aha',
          'hash',
          'jak',
          'fads',
          'lads',
        ],
        120,
      ),
    ],
  },
];

// ---- Unit 2: Top Row ----
const topRow: Builder[] = [
  {
    id: 'tr.01.e',
    title: 'Key: E',
    summary: 'Left middle reaches up to E and returns home.',
    steps: [
      intro('e', 'L_MIDDLE', 'Reach your left middle finger up from D to E, then return.'),
      drill('e e e e e e e e e e'),
      drill('ded ded ded ded ded ded'),
      drill('eed dee eed dee eed dee'),
      drill('elf see deed feed desk lead'),
    ],
  },
  {
    id: 'tr.02.i',
    title: 'Key: I',
    summary: 'Right middle reaches up to I and returns home.',
    steps: [
      intro('i', 'R_MIDDLE', 'Reach your right middle finger up from K to I.'),
      drill('i i i i i i i i i i'),
      drill('kik kik kik kik kik kik'),
      drill('iik kii iik kii iik kii'),
      drill('like skid kind hike inside idle'),
    ],
  },
  {
    id: 'tr.03.ei',
    title: 'E & I',
    summary: 'Alternate E and I with home row keys.',
    steps: [
      drill('ei ei ei ie ie ie ei ie'),
      drill('ded kik ded kik ded kik ded'),
      drill('die dies kids side hide aide'),
      drill('field shield jellied idle eke'),
      drill('he did flee she sees kids side'),
    ],
  },
  {
    id: 'tr.04.r',
    title: 'Key: R',
    summary: 'Left index reaches up to R and returns home.',
    steps: [
      intro('r', 'L_INDEX', 'Left index reaches up from F to R.'),
      drill('r r r r r r r r r r'),
      drill('frf frf frf frf frf frf'),
      drill('rrf frr rrf frr rrf frr'),
      drill('red ref read rear rare rides'),
    ],
  },
  {
    id: 'tr.05.u',
    title: 'Key: U',
    summary: 'Right index reaches up to U and returns home.',
    steps: [
      intro('u', 'R_INDEX', 'Right index reaches up from J to U.'),
      drill('u u u u u u u u u u'),
      drill('juj juj juj juj juj juj'),
      drill('uuj juu uuj juu uuj juu'),
      drill('us use used hush just dusk'),
    ],
  },
  {
    id: 'tr.06.ru',
    title: 'R & U',
    summary: 'Alternate R and U with earlier keys.',
    steps: [
      drill('ru ru ru ur ur ur ru ur'),
      drill('fru juf fru juf fru juf fru'),
      drill('rude rues rush ruse rusk rule'),
      drill('ruler surer erred drier rural'),
      drill('her fur sure rider ruder user'),
    ],
  },
  {
    id: 'tr.07.test1',
    title: 'Test: Inner Top',
    summary: 'Timed drill on E I R U with home row.',
    steps: [
      practice(
        [
          'dire',
          'rides',
          'sure',
          'ruse',
          'ride',
          'dude',
          'side',
          'hike',
          'rise',
          'idle',
          'userid',
          'surer',
          'riskier',
          'slide',
          'jelly',
          'freer',
          'shuler',
          'users',
          'drudge',
          'kidless',
          'healed',
          'field',
          'skies',
          'irksid',
          'friskier',
        ],
        75,
      ),
    ],
  },
  {
    id: 'tr.08.t',
    title: 'Key: T',
    summary: 'Left index stretches up to T.',
    steps: [
      intro('t', 'L_INDEX', 'Left index stretches up to T — same finger as F, G, R.'),
      drill('t t t t t t t t t t'),
      drill('tft tft tft tft tft tft'),
      drill('ttf ftt ttf ftt ttf ftt'),
      drill('the tilt treat trust stout tasted'),
    ],
  },
  {
    id: 'tr.09.y',
    title: 'Key: Y',
    summary: 'Right index stretches up to Y.',
    steps: [
      intro('y', 'R_INDEX', 'Right index stretches up to Y — same finger as J, H, U.'),
      drill('y y y y y y y y y y'),
      drill('yjy yjy yjy yjy yjy yjy'),
      drill('yyj jyy yyj jyy yyj jyy'),
      drill('yes yell yard yoke yours yearly'),
    ],
  },
  {
    id: 'tr.10.ty',
    title: 'T & Y',
    summary: 'Alternate T and Y with earlier keys.',
    steps: [
      drill('ty ty ty yt yt yt ty yt ty yt'),
      drill('try yet try yet try yet try yet'),
      drill('they style tray yard yeast testy'),
      drill('yester tryst trusty thirty thrift'),
      drill('the truth yet there try it freely'),
    ],
  },
  {
    id: 'tr.11.w',
    title: 'Key: W',
    summary: 'Left ring reaches up to W.',
    steps: [
      intro('w', 'L_RING', 'Left ring reaches up from S to W.'),
      drill('w w w w w w w w w w'),
      drill('sws sws sws sws sws sws'),
      drill('wws sww wws sww wws sww'),
      drill('we was wit wes wide wish'),
    ],
  },
  {
    id: 'tr.12.o',
    title: 'Key: O',
    summary: 'Right ring reaches up to O.',
    steps: [
      intro('o', 'R_RING', 'Right ring reaches up from L to O.'),
      drill('o o o o o o o o o o'),
      drill('lol lol lol lol lol lol'),
      drill('ool loo ool loo ool loo'),
      drill('old out owl okay outer oddly'),
    ],
  },
  {
    id: 'tr.13.wo',
    title: 'W & O',
    summary: 'Alternate W and O with tricky mixes.',
    steps: [
      drill('wo wo wo ow ow ow wo ow wo ow'),
      drill('sws lol sws lol sws lol sws lol'),
      drill('word work wool wood sword woods'),
      drill('wows swoop wordy outflow worthy'),
      drill('we owe two words toward willow'),
    ],
  },
  {
    id: 'tr.14.q',
    title: 'Key: Q',
    summary: 'Left pinky reaches up to Q.',
    steps: [
      intro('q', 'L_PINKY', 'Left pinky reaches up from A to Q.'),
      drill('q q q q q q q q q q'),
      drill('aqa aqa aqa aqa aqa aqa'),
      drill('qqa aqq qqa aqq qqa aqq'),
      drill('qui quay quit quid quirk quest'),
    ],
  },
  {
    id: 'tr.15.p',
    title: 'Key: P',
    summary: 'Right pinky reaches up to P.',
    steps: [
      intro('p', 'R_PINKY', 'Right pinky reaches up from ; to P.'),
      drill('p p p p p p p p p p'),
      drill(';p; ;p; ;p; ;p; ;p; ;p;'),
      drill('pp; ;pp pp; ;pp pp; ;pp'),
      drill('pop put pup pipe poker purply'),
    ],
  },
  {
    id: 'tr.16.qp',
    title: 'Q & P',
    summary: 'Pinky stretches — Q and P mixed with earlier keys.',
    steps: [
      drill('qp qp qp pq pq pq qp pq qp pq'),
      drill('quip quip quip quid quid quid'),
      drill('quit pop put pup quip papa quirks'),
      drill('puppy quiet perhaps proper appeal'),
      drill('a quiet papa kept pups quite properly'),
    ],
  },
  {
    id: 'tr.17.full',
    title: 'Full Top Row',
    summary: 'Every top row key mixed with home row.',
    steps: [
      drill('qwerty uiop qwerty uiop qwerty uiop'),
      drill('the quiet wolf yields poetry outside'),
      drill('we type words quietly into the paper'),
      drill('eighty riper yelp squash trifle ought'),
      drill('you quote the proud poet her quiet reply'),
    ],
  },
  {
    id: 'tr.18.test2',
    title: 'Test: Top Row',
    summary: 'Long timed practice across the entire top row.',
    steps: [
      practice(
        [
          'quiet',
          'yield',
          'paper',
          'power',
          'puppy',
          'watch',
          'world',
          'poetry',
          'route',
          'there',
          'weird',
          'proud',
          'youth',
          'quote',
          'tower',
          'water',
          'prepare',
          'outside',
          'reply',
          'utter',
          'query',
          'quilt',
          'sturdy',
          'trophy',
          'wisdom',
          'output',
          'worth',
          'tries',
          'thirty',
          'superior',
        ],
        120,
      ),
    ],
  },
];

// ---- Unit 3: Bottom Row ----
const bottomRow: Builder[] = [
  {
    id: 'br.01.v',
    title: 'Key: V',
    summary: 'Left index drops down from F to V.',
    steps: [
      intro('v', 'L_INDEX', 'Left index reaches down from F to V — same finger as F and G.'),
      drill('v v v v v v v v v v'),
      drill('fvf fvf fvf fvf fvf fvf'),
      drill('vfv vfv fvf vfv fvf vfv fvf'),
      drill('vf vf fv fv vfv fvf vff fvv'),
    ],
  },
  {
    id: 'br.02.n',
    title: 'Key: N',
    summary: 'Right index drops down from J to N.',
    steps: [
      intro('n', 'R_INDEX', 'Right index reaches down from J to N — same finger as J and H.'),
      drill('n n n n n n n n n n'),
      drill('jnj jnj jnj jnj jnj jnj'),
      drill('njn njn jnj njn jnj njn jnj'),
      drill('nj nj jn jn njn jnj njj jnn'),
    ],
  },
  {
    id: 'br.03.vn',
    title: 'V & N',
    summary: 'Alternate V and N across both hands.',
    steps: [
      drill('vn vn vn vn vn nv nv nv nv'),
      drill('vnv nvn vnv nvn vnv nvn vnv'),
      drill('van van nav nav van nav van nav'),
      drill('never seven envy vain vein noun'),
      drill('ivan vent nova niven even naive'),
    ],
  },
  {
    id: 'br.04.c',
    title: 'Key: C',
    summary: 'Left middle drops down from D to C.',
    steps: [
      intro('c', 'L_MIDDLE', 'Left middle reaches down from D to C.'),
      drill('c c c c c c c c c c'),
      drill('dcd dcd dcd dcd dcd dcd'),
      drill('cdc cdc dcd cdc dcd cdc dcd'),
      drill('cd dc cdc dcd ccd dcc cdd'),
    ],
  },
  {
    id: 'br.05.m',
    title: 'Key: M',
    summary: 'Right index drops down from J to M.',
    steps: [
      intro('m', 'R_INDEX', 'Right index reaches down from J to M — next to N.'),
      drill('m m m m m m m m m m'),
      drill('jmj jmj jmj jmj jmj jmj'),
      drill('mjm mjm jmj mjm jmj mjm jmj'),
      drill('mj jm mjm jmj mmj jmm mjj'),
    ],
  },
  {
    id: 'br.06.cm',
    title: 'C & M',
    summary: 'Mix C and M with earlier bottom row.',
    steps: [
      drill('cm cm cm cm cm mc mc mc mc'),
      drill('cmc mcm cmc mcm cmc mcm cmc'),
      drill('come cue mine camp calm much more'),
      drill('micro comma march music cream mercy'),
      drill('venom cinema vacuum moment cactus'),
    ],
  },
  {
    id: 'br.07.test1',
    title: 'Test: Bottom Inner',
    summary: 'Seventy-five second drill on v n c m.',
    steps: [
      practice(
        [
          'come',
          'mine',
          'cave',
          'name',
          'move',
          'much',
          'none',
          'menu',
          'vine',
          'numb',
          'mace',
          'dance',
          'crime',
          'cover',
          'mango',
          'ocean',
          'venom',
          'canoe',
          'manic',
          'cabin',
          'comic',
          'voice',
          'cinema',
          'moment',
          'common',
        ],
        75,
      ),
    ],
  },
  {
    id: 'br.08.x',
    title: 'Key: X',
    summary: 'Left ring drops down from S to X.',
    steps: [
      intro('x', 'L_RING', 'Left ring reaches down from S to X.'),
      drill('x x x x x x x x x x'),
      drill('sxs sxs sxs sxs sxs sxs'),
      drill('xsx xsx sxs xsx sxs xsx sxs'),
      drill('xs sx xsx sxs xxs sxx xss'),
    ],
  },
  {
    id: 'br.09.comma',
    title: 'Key: ,',
    summary: 'Right middle drops down from K to comma.',
    steps: [
      intro(',', 'R_MIDDLE', 'Right middle reaches down from K to comma.'),
      drill(', , , , , , , , , ,'),
      drill('k,k k,k k,k k,k k,k k,k'),
      drill(',k, ,k, k,k ,k, k,k ,k, k,k'),
      drill('k, ,k k,k ,k, k,, ,,k ,k,'),
    ],
  },
  {
    id: 'br.10.xcomma',
    title: 'X & ,',
    summary: 'Alternate left ring X with right middle comma.',
    steps: [
      drill('x, x, x, x, ,x ,x ,x ,x'),
      drill('x,x ,x, x,x ,x, x,x ,x, x,x'),
      drill('six, mix, box, fox, fix, wax, tax,'),
      drill('axis, toxic, exit, extra, relax,'),
      drill('six foxes, mix axes, exact exit,'),
    ],
  },
  {
    id: 'br.11.z',
    title: 'Key: Z',
    summary: 'Left pinky drops down from A to Z.',
    steps: [
      intro('z', 'L_PINKY', 'Left pinky reaches down from A to Z.'),
      drill('z z z z z z z z z z'),
      drill('aza aza aza aza aza aza'),
      drill('zaz zaz aza zaz aza zaz aza'),
      drill('za az zaz aza zza azz zaa'),
    ],
  },
  {
    id: 'br.12.period',
    title: 'Key: .',
    summary: 'Right ring drops down from L to period.',
    steps: [
      intro('.', 'R_RING', 'Right ring reaches down from L to period.'),
      drill('. . . . . . . . . .'),
      drill('l.l l.l l.l l.l l.l l.l'),
      drill('.l. .l. l.l .l. l.l .l. l.l'),
      drill('l. .l l.l .l. l.. ..l .l.'),
    ],
  },
  {
    id: 'br.13.zperiod',
    title: 'Z & .',
    summary: 'Pinky Z meets ring-finger period.',
    steps: [
      drill('z. z. z. z. .z .z .z .z'),
      drill('z.z .z. z.z .z. z.z .z. z.z'),
      drill('zoo. maze. zip. size. zero.'),
      drill('dozen. zone. crazy. freeze. hazy.'),
      drill('a zebra dozed. the maze froze.'),
    ],
  },
  {
    id: 'br.14.b',
    title: 'Key: B',
    summary: 'Left index stretches right to B.',
    steps: [
      intro('b', 'L_INDEX', 'Left index stretches right to B — same finger as F, V, G.'),
      drill('b b b b b b b b b b'),
      drill('fbf fbf fbf fbf fbf fbf'),
      drill('bfb bfb fbf bfb fbf bfb fbf'),
      drill('bf fb bfb fbf bbf fbb bff'),
    ],
  },
  {
    id: 'br.15.slash',
    title: 'Key: /',
    summary: 'Right pinky drops down to slash.',
    steps: [
      intro('/', 'R_PINKY', 'Right pinky reaches down from ; to slash.'),
      drill('/ / / / / / / / / /'),
      drill(';/; ;/; ;/; ;/; ;/; ;/;'),
      drill('/;/ /;/ ;/; /;/ ;/; /;/ ;/;'),
      drill('/; ;/ /;/ ;/; //; ;// /;;'),
    ],
  },
  {
    id: 'br.16.bslash',
    title: 'B & /',
    summary: 'Index B meets pinky slash.',
    steps: [
      drill('b/ b/ b/ b/ /b /b /b /b'),
      drill('b/b /b/ b/b /b/ b/b /b/ b/b'),
      drill('by/ be/ but/ big/ bad/ bus/'),
      drill('build/ both/ back/ brave/ broad/'),
      drill('abort/ bottle/ rabbit/ bubble/'),
    ],
  },
  {
    id: 'br.17.full',
    title: 'Full Bottom Row',
    summary: 'Every bottom-row key mixed with earlier rows.',
    steps: [
      drill('zxcvb nm,./ zxcvb nm,./ zxcvb nm,./'),
      drill('/.,mn bvcxz /.,mn bvcxz /.,mn bvcxz'),
      drill('zx cv bn m, ./ zx cv bn m, ./ zx cv'),
      drill('brown cat moves over seven lazy mice.'),
      drill('a quick zebra jumps, next vanish away.'),
    ],
  },
  {
    id: 'br.18.test2',
    title: 'Test: All Letters',
    summary: 'Two-minute drill across the full alphabet.',
    steps: [
      practice(
        [
          'quick',
          'brown',
          'jumps',
          'over',
          'lazy',
          'foxes',
          'never',
          'cabin',
          'seven',
          'maze',
          'vanish',
          'climb',
          'breeze',
          'music',
          'happy',
          'zebra',
          'frozen',
          'galaxy',
          'wizard',
          'jacket',
          'quartz',
          'eighty',
          'voyage',
          'plexus',
          'knight',
          'puzzle',
          'dreamy',
          'oxygen',
        ],
        120,
      ),
    ],
  },
];

// ---- Unit 4: Shift & Capitals ----
const shifts: Builder[] = [
  {
    id: 'sh.01.left',
    title: 'Left Shift',
    summary: 'Hold left shift with your left pinky to type right-hand capitals.',
    steps: [
      intro(
        'J',
        'R_INDEX',
        'Hold LEFT SHIFT with your left pinky while your right index taps J. Your left pinky does the shifting for every right-hand letter.',
      ),
      drill('J J J H H H U U U M M M', 'Left pinky holds shift for every letter. Release between capitals.'),
      drill('Jack Hill Urge Myth Know', 'Left pinky stays on shift while the right hand types.'),
      drill('Hi Jo Kim Luke Nick Paul Owen', 'Left pinky shift — right-hand capitals only.'),
      drill('Mount Umbra Plumb Honey Kayak Ivory', 'Keep the left pinky anchored on shift through every capital.'),
    ],
  },
  {
    id: 'sh.02.right',
    title: 'Right Shift',
    summary: 'Hold right shift with your right pinky to type left-hand capitals.',
    steps: [
      intro(
        'F',
        'L_INDEX',
        'Hold RIGHT SHIFT with your right pinky while your left index taps F. Your right pinky does the shifting for every left-hand letter.',
      ),
      drill('F F F D D D S S S A A A', 'Right pinky holds shift for every letter. Release between capitals.'),
      drill('Fast Drum Safe Able Ever', 'Right pinky stays on shift while the left hand types.'),
      drill('Tea Rex Cab Vow Bee Was Gem', 'Right pinky shift — left-hand capitals only.'),
      drill('Quack Zebra Xenon Waves Craft Trade', 'Keep the right pinky anchored on shift through every capital.'),
    ],
  },
  {
    id: 'sh.03.mix',
    title: 'Shift Drill',
    summary: 'Alternate hands to pick the right shift key for each capital.',
    steps: [
      drill('Fun Joy Sad Kid Ram Yes Nod Eve Tom', 'Letter on the left? Right shift. Letter on the right? Left shift.'),
      drill('Apple Banana Clever Dance Echo Falcon', 'Each word starts with a single capital — pick the opposite shift.'),
      drill('The Quick Brown Fox Jumps Over Lazy Dog', 'Classic pangram, capitalized — swap shifts as you go.'),
      drill('Mary Had A Little Lamb At School', 'Short words, lots of shifting.'),
      drill('Hello From New York To San Diego', 'Alternate left and right shifts for each capitalized word.'),
    ],
  },
  {
    id: 'sh.04.test1',
    title: 'Test: Capitalized Words',
    summary: 'Timed run of single capitalized words.',
    steps: [
      practice(
        [
          'Alpha',
          'Bravo',
          'Charlie',
          'Delta',
          'Echo',
          'Foxtrot',
          'Golf',
          'Hotel',
          'India',
          'Juliet',
          'Kilo',
          'Lima',
          'Mike',
          'November',
          'Oscar',
          'Papa',
          'Quebec',
          'Romeo',
          'Sierra',
          'Tango',
          'Uniform',
          'Victor',
          'Whiskey',
          'Xray',
          'Yankee',
          'Zulu',
        ],
        75,
      ),
    ],
  },
  {
    id: 'sh.05.excl_q',
    title: '! and ?',
    summary: 'Exclamation points and question marks with proper shift technique.',
    steps: [
      intro('!', 'L_PINKY', 'Exclamation is shift+1. Hold RIGHT shift with your right pinky, then the left pinky taps 1.'),
      intro('?', 'R_PINKY', 'Question mark is shift+/. Hold LEFT shift with your left pinky, then the right pinky taps /.'),
      drill('Yes! No? Go! Why? Wow! Who? Stop! When?', 'Short bursts — release shift between each mark.'),
      drill('Watch out! Are you sure? That was amazing!', 'Full phrases. Shift changes hands often.'),
      drill('Hello there! How are you today? I am great!', 'Capitals plus punctuation in one flow.'),
    ],
  },
  {
    id: 'sh.06.quotes',
    title: 'Quotes and Colon',
    summary: 'Double quotes and colons inside real phrases.',
    steps: [
      intro('"', 'R_PINKY', "Double quote is shift+'. Hold LEFT shift with your left pinky, then the right pinky taps the apostrophe key."),
      intro(':', 'R_PINKY', 'Colon is shift+;. Hold LEFT shift with your left pinky, then the right pinky taps the semicolon key.'),
      drill('She said: "Hello there, friend."', 'Colon, space, open quote, phrase, close quote.'),
      drill('Warning: "Do not touch the wet paint!"', 'Colon introduces a quoted warning.'),
      drill('Answer: "Yes, I can help you today."', 'Mix capitals, quotes, colons, and a period.'),
    ],
  },
  {
    id: 'sh.07.sentences',
    title: 'Sentences',
    summary: 'Full sentences with mixed capitalization and punctuation.',
    steps: [
      drill('The cat sat quietly on the soft mat.', 'One capital at the start, one period at the end.'),
      drill('We went to the park today and had great fun!', 'Exclamation at the end — shift once more.'),
      drill('Is this the right answer to the question?', 'Question mark needs left shift on the slash.'),
      drill('Sarah said: "Let us walk to the library now."', 'Capitals, colon, quotes, and a period.'),
      drill('My friend Jack asked: "Where did you go last week?"', 'Two capitals, a colon, quotes, and a question mark.'),
    ],
  },
  {
    id: 'sh.08.test2',
    title: 'Test: Mixed Case',
    summary: 'Timed mixed-case phrase practice.',
    steps: [
      practice(
        [
          'Hello World',
          'Good Morning',
          'See You Soon',
          'Thank You',
          'Nice To Meet You',
          'How Are You',
          'Have A Great Day',
          'Quick Brown Fox',
          'Lazy Dog',
          'Never Give Up',
          'Keep Going',
          'You Got This',
          'Well Done',
          'Try Again',
          'Almost There',
          'Stay Focused',
          'Practice Daily',
          'Rise And Shine',
          'Think Twice',
          'Speak Clearly',
          'Read Slowly',
          'Write Neatly',
          'Listen Well',
          'Learn Fast',
          'Dream Big',
        ],
        120,
      ),
    ],
  },
];

// ---- Unit 5: Numbers ----
const numbers: Builder[] = [
  {
    id: 'nm.01.4',
    title: 'Key: 4',
    summary: 'Left index reaches way up to 4.',
    steps: [
      intro('4', 'L_INDEX', 'Left index reaches up to 4 — above R.'),
      drill('f4f f4f f4f f4f f4f f4f'),
      drill('4f4 f44 4f4 f44 4f4 f44'),
      drill('f4 f4 f4 f4 f4 f4 f4 f4'),
      drill('44f f44 44f f44 44f f44'),
    ],
  },
  {
    id: 'nm.02.7',
    title: 'Key: 7',
    summary: 'Right index reaches way up to 7.',
    steps: [
      intro('7', 'R_INDEX', 'Right index reaches up to 7 — above U.'),
      drill('j7j j7j j7j j7j j7j j7j'),
      drill('7j7 j77 7j7 j77 7j7 j77'),
      drill('j7 j7 j7 j7 j7 j7 j7 j7'),
      drill('77j j77 77j j77 77j j77'),
    ],
  },
  {
    id: 'nm.03.47',
    title: '4 & 7',
    summary: 'Index numbers — 4 and 7.',
    steps: [
      drill('47 74 47 74 47 74 47 74'),
      drill('447 774 447 774 447 774'),
      drill('4747 7474 4747 7474 47'),
      drill('f4j7 f4j7 f4j7 f4j7 f4j7'),
      drill('74 47 74 47 477 744 477'),
    ],
  },
  {
    id: 'nm.04.3',
    title: 'Key: 3',
    summary: 'Left middle reaches up to 3.',
    steps: [
      intro('3', 'L_MIDDLE', 'Left middle reaches up to 3 — above E.'),
      drill('d3d d3d d3d d3d d3d d3d'),
      drill('3d3 d33 3d3 d33 3d3 d33'),
      drill('d3 d3 d3 d3 d3 d3 d3 d3'),
      drill('33d d33 33d d33 33d d33'),
    ],
  },
  {
    id: 'nm.05.8',
    title: 'Key: 8',
    summary: 'Right middle reaches up to 8.',
    steps: [
      intro('8', 'R_MIDDLE', 'Right middle reaches up to 8 — above I.'),
      drill('k8k k8k k8k k8k k8k k8k'),
      drill('8k8 k88 8k8 k88 8k8 k88'),
      drill('k8 k8 k8 k8 k8 k8 k8 k8'),
      drill('88k k88 88k k88 88k k88'),
    ],
  },
  {
    id: 'nm.06.38',
    title: '3 & 8',
    summary: 'Middle numbers — 3 and 8.',
    steps: [
      drill('38 83 38 83 38 83 38 83'),
      drill('338 883 338 883 338 883'),
      drill('3478 8743 3478 8743 3478'),
      drill('d3k8 d3k8 d3k8 d3k8 d3k8'),
      drill('83 38 8383 3838 838 383'),
    ],
  },
  {
    id: 'nm.07.test1',
    title: 'Test: Inner Numbers',
    summary: '3 4 7 8 timed practice.',
    steps: [
      practice(
        [
          '34',
          '78',
          '347',
          '874',
          '3478',
          '8743',
          '4738',
          '7384',
          '3344',
          '7788',
          '4873',
          '7348',
          '8437',
          '3874',
          '7843',
          '4387',
          '8734',
          '3748',
          '4378',
          '7834',
          '8347',
          '3784',
          '4873',
          '8473',
        ],
        75,
      ),
    ],
  },
  {
    id: 'nm.08.5',
    title: 'Key: 5',
    summary: 'Left index stretches to 5.',
    steps: [
      intro('5', 'L_INDEX', 'Left index stretches up to 5 — above T.'),
      drill('f5f f5f f5f f5f f5f f5f'),
      drill('5f5 f55 5f5 f55 5f5 f55'),
      drill('f5 f5 f5 f5 f5 f5 f5 f5'),
      drill('55f f55 455 554 455 554'),
    ],
  },
  {
    id: 'nm.09.6',
    title: 'Key: 6',
    summary: 'Right index stretches to 6.',
    steps: [
      intro('6', 'R_INDEX', 'Right index stretches up to 6 — above Y.'),
      drill('j6j j6j j6j j6j j6j j6j'),
      drill('6j6 j66 6j6 j66 6j6 j66'),
      drill('j6 j6 j6 j6 j6 j6 j6 j6'),
      drill('66j j66 766 667 766 667'),
    ],
  },
  {
    id: 'nm.10.56',
    title: '5 & 6',
    summary: 'Index stretches — 5 and 6.',
    steps: [
      drill('56 65 56 65 56 65 56 65'),
      drill('556 665 556 665 556 665'),
      drill('3456 6543 3456 6543 3456'),
      drill('f5j6 f5j6 f5j6 f5j6 f5j6'),
      drill('456 654 565 656 4565 6546'),
    ],
  },
  {
    id: 'nm.11.2',
    title: 'Key: 2',
    summary: 'Left ring reaches up to 2.',
    steps: [
      intro('2', 'L_RING', 'Left ring reaches up to 2 — above W.'),
      drill('s2s s2s s2s s2s s2s s2s'),
      drill('2s2 s22 2s2 s22 2s2 s22'),
      drill('s2 s2 s2 s2 s2 s2 s2 s2'),
      drill('22s s22 223 322 223 322'),
    ],
  },
  {
    id: 'nm.12.9',
    title: 'Key: 9',
    summary: 'Right ring reaches up to 9.',
    steps: [
      intro('9', 'R_RING', 'Right ring reaches up to 9 — above O.'),
      drill('l9l l9l l9l l9l l9l l9l'),
      drill('9l9 l99 9l9 l99 9l9 l99'),
      drill('l9 l9 l9 l9 l9 l9 l9 l9'),
      drill('99l l99 899 998 899 998'),
    ],
  },
  {
    id: 'nm.13.29',
    title: '2 & 9',
    summary: 'Ring numbers — 2 and 9.',
    steps: [
      drill('29 92 29 92 29 92 29 92'),
      drill('234 789 234 789 234 789'),
      drill('23456 78901 23456 78901'),
      drill('s2l9 s2l9 s2l9 s2l9 s2l9'),
      drill('292 929 2992 9229 292 929'),
    ],
  },
  {
    id: 'nm.14.1',
    title: 'Key: 1',
    summary: 'Left pinky reaches up to 1.',
    steps: [
      intro('1', 'L_PINKY', 'Left pinky reaches up to 1 — above Q.'),
      drill('a1a a1a a1a a1a a1a a1a'),
      drill('1a1 a11 1a1 a11 1a1 a11'),
      drill('a1 a1 a1 a1 a1 a1 a1 a1'),
      drill('11a a11 112 211 112 211'),
    ],
  },
  {
    id: 'nm.15.0',
    title: 'Key: 0',
    summary: 'Right pinky reaches up to 0.',
    steps: [
      intro('0', 'R_PINKY', 'Right pinky reaches up to 0 — above P.'),
      drill(';0; ;0; ;0; ;0; ;0; ;0;'),
      drill('0;0 ;00 0;0 ;00 0;0 ;00'),
      drill(';0 ;0 ;0 ;0 ;0 ;0 ;0 ;0'),
      drill('00; ;00 900 009 900 009'),
    ],
  },
  {
    id: 'nm.16.10',
    title: '1 & 0',
    summary: 'Pinky numbers — 1 and 0.',
    steps: [
      drill('10 01 10 01 10 01 10 01'),
      drill('101 010 101 010 101 010'),
      drill('1234567890 1234567890'),
      drill('a1;0 a1;0 a1;0 a1;0 a1;0'),
      drill('100 010 001 1001 0110 100'),
    ],
  },
  {
    id: 'nm.17.full',
    title: 'Full Number Row',
    summary: 'All numbers.',
    steps: [
      drill('1234567890 1234567890 12345'),
      drill('0987654321 0987654321 09876'),
      drill('13579 24680 13579 24680 13579'),
      drill('2 4 6 8 10 12 14 16 18 20'),
      drill('5 10 15 20 25 30 35 40 45 50'),
    ],
  },
  {
    id: 'nm.18.test2',
    title: 'Test: Numbers',
    summary: 'Timed number practice.',
    steps: [
      practice(
        [
          '1776',
          '1984',
          '2026',
          '1969',
          '1492',
          '2001',
          '1945',
          '1865',
          '1066',
          '1215',
          '19.99',
          '4.50',
          '125.00',
          '7.25',
          '42',
          '365',
          '3.14159',
          '2.71828',
          '90210',
          '10001',
          '60601',
          '94103',
          '02/14/2026',
          '07/04/1776',
          '12/25/2024',
          '911',
          '411',
          '1000000',
        ],
        90,
      ),
    ],
  },
];

// ---- Unit 6: Symbols ----
const symbols: Builder[] = [
  {
    id: 'sy.01.dash_eq',
    title: '- and =',
    summary: 'Dash and equals — right pinky reaches to the top-right corner.',
    steps: [
      intro('-', 'R_PINKY', 'Right pinky reaches up-right to dash.'),
      intro('=', 'R_PINKY', 'Right pinky reaches up-right to equals.'),
      drill('-= -= -= -= -= -= -=', 'Alternate dash and equals cleanly.'),
      drill('x=1, y=2, z=3-4, w=5-6', 'Simple assignments and subtractions.'),
      drill('a-b=c, d-e=f, 10-3=7, 8-2=6'),
    ],
  },
  {
    id: 'sy.02.brackets',
    title: 'Brackets [ ]',
    summary: 'Right pinky reaches up for square brackets.',
    steps: [
      intro('[', 'R_PINKY', 'Right pinky reaches up to [.'),
      intro(']', 'R_PINKY', 'Right pinky reaches up to ].'),
      drill('[] [] [] [] [] [] []', 'Open then close, no delay.'),
      drill('a[0] b[1] c[2] d[3] e[4]', 'Array indexing pattern.'),
      drill('list[i] = arr[j] + arr[k-1]'),
    ],
  },
  {
    id: 'sy.03.slash_back',
    title: '\\ and `',
    summary: 'Backslash with right pinky, backtick with left pinky.',
    steps: [
      intro('\\', 'R_PINKY', 'Right pinky reaches up to backslash.'),
      intro('`', 'L_PINKY', 'Left pinky reaches up-left to backtick.'),
      drill('`\\ `\\ `\\ `\\ `\\ `\\', 'Alternate backtick and backslash.'),
      drill('C:\\Users\\me\\docs\\file.txt', 'Windows-style path.'),
      drill('`code` and `echo hi` in \\bin\\sh'),
    ],
  },
  {
    id: 'sy.04.shift_nums1',
    title: '! @ # $ %',
    summary: 'Shifted top row, keys 1 through 5.',
    steps: [
      drill('! @ # $ % ! @ # $ %', 'Shift + 1, 2, 3, 4, 5.'),
      drill('Wow! $19.99 only! 50% off!', 'Exclamations and a price.'),
      drill('email me @ user@site.com today', 'At-sign in an address.'),
      drill('#intro #test #42 #todo #done', 'Hashtag list.'),
      drill('tax is 8%, tip 20%, total $45.60'),
    ],
  },
  {
    id: 'sy.05.shift_nums2',
    title: '^ & * ( )',
    summary: 'Shifted top row, keys 6 through 0.',
    steps: [
      drill('^ & * ( ) ^ & * ( )', 'Shift + 6, 7, 8, 9, 0.'),
      drill('(x + y) * 2 = (a & b)', 'Parens with a math expression.'),
      drill('2^8 = 256, 3^2 = 9, 10^3', 'Power notation with caret.'),
      drill('foo(a, b) && bar(c, d)', 'Function calls with logical and.'),
      drill('ptr* = &val; list[*i]++;'),
    ],
  },
  {
    id: 'sy.06.shifted_punct',
    title: '_ + { } |',
    summary: 'Shifted dash, equals, brackets, and pipe.',
    steps: [
      drill('_ + { } | _ + { } |', 'Shift + -, =, [, ], \\.'),
      drill('{name: "Ada", age: 36}', 'Object literal with quoted key.'),
      drill('user_id + post_id = key_1', 'Underscores in identifiers.'),
      drill('cat log.txt | grep ERROR | wc', 'Shell pipe chain.'),
      drill('snake_case + camelCase = mix_4'),
    ],
  },
  {
    id: 'sy.07.shift_other',
    title: '~ < > ?',
    summary: 'Tilde, comparisons, and question mark.',
    steps: [
      drill('~ < > ? ~ < > ? ~ < > ?', 'Shift + `, ,, ., /.'),
      drill('<div>Hello, world!</div>', 'HTML-ish tag pair.'),
      drill('cd ~/docs && ls ~/.config', 'Home directory paths.'),
      drill('if (x < 5 && y > 10) { ok? }', 'Conditional with comparisons.'),
      drill('a -> b -> c, are we there yet?'),
    ],
  },
  {
    id: 'sy.08.test',
    title: 'Test: Symbols',
    summary: 'Timed mixed symbol practice with realistic tokens.',
    steps: [
      practice(
        [
          '$19.99',
          '100%',
          '#42',
          '(x,y)',
          '{k:v}',
          '[i]',
          '<div>',
          'a+b',
          'x=y',
          'n/a',
          '~/.config',
          'a->b',
          'user@site.com',
          'C:\\dir',
          '(a&b)',
          '2^8',
          'foo()',
          'arr[0]',
          'p|q',
          '!done',
          '50%',
          '$5.00',
          '#todo',
          'x_y',
          '<3',
          'end?',
          '`cmd`',
          '{a,b}',
        ],
        120,
      ),
    ],
  },
];

// ---- Unit 7: Speed Building ----
const speed: Builder[] = [
  {
    id: 'sp.01.common1',
    title: 'Common Words I',
    summary: 'Drill the highest-frequency English words for raw speed.',
    steps: [
      words([
        'the',
        'of',
        'and',
        'to',
        'a',
        'in',
        'is',
        'you',
        'that',
        'it',
        'he',
        'was',
        'for',
        'on',
        'are',
        'as',
        'with',
        'his',
        'they',
        'at',
        'be',
        'this',
        'have',
        'from',
        'or',
        'one',
        'had',
        'by',
        'word',
        'but',
        'not',
        'what',
        'all',
        'were',
        'we',
      ]),
    ],
  },
  {
    id: 'sp.02.common2',
    title: 'Common Words II',
    summary: 'More high-frequency words to push sustained pace.',
    steps: [
      words([
        'when',
        'your',
        'can',
        'said',
        'there',
        'use',
        'each',
        'which',
        'she',
        'do',
        'how',
        'their',
        'if',
        'will',
        'up',
        'other',
        'about',
        'out',
        'many',
        'then',
        'them',
        'these',
        'so',
        'some',
        'her',
        'would',
        'make',
        'like',
        'him',
        'into',
        'time',
        'has',
        'look',
        'two',
        'more',
      ]),
    ],
  },
  {
    id: 'sp.03.sentences1',
    title: 'Sentences I',
    summary: 'Short sentences and classic pangrams.',
    steps: [
      drill('The quick brown fox jumps over the lazy dog.'),
      drill('Pack my box with five dozen liquor jugs.'),
      drill('How vexingly quick daft zebras jump!'),
      drill('Sphinx of black quartz, judge my vow.'),
      drill('The five boxing wizards jump quickly every night.'),
    ],
  },
  {
    id: 'sp.04.sentences2',
    title: 'Sentences II',
    summary: 'Longer sentences with punctuation, numbers, and mixed case.',
    steps: [
      drill('"Hello, world!" said the robot, slowly and with surprising care.'),
      drill('In 2026, nearly 42% of students learned to type at 100+ WPM.'),
      drill('She asked, "Can you meet me at 9:30 a.m. on Tuesday, April 14?"'),
      drill('Order #4872 shipped on 03/15/2025 from Seattle to New York City.'),
      drill('"Focus, breathe, and keep going," he whispered — then pressed Enter.'),
    ],
  },
  {
    id: 'sp.05.paragraph',
    title: 'Paragraph',
    summary: 'Multi-sentence paragraphs to build endurance and rhythm.',
    steps: [
      drill(
        'Typing well is a quiet kind of craft. The more you practice with purpose, the faster your fingers will find the keys on their own. Keep your wrists light, your eyes on the screen, and let the rhythm carry you forward, one word at a time.',
      ),
      drill(
        'Learning anything new is rarely a straight line. You will have slow days, clumsy days, and days when every key feels wrong. Show up anyway. Small, steady sessions compound into real skill, and the progress you cannot feel today becomes the habit you rely on tomorrow.',
      ),
      drill(
        'Modern technology rewards people who can move ideas quickly from their head to the screen. A fast, accurate typist writes emails, code, and essays with less friction, which leaves more room for thinking. The keyboard becomes less of a tool and more of an extension of the mind.',
      ),
    ],
  },
  {
    id: 'sp.06.final',
    title: 'Final Test',
    summary: 'Three-minute sustained typing test on common English words.',
    steps: [
      practice(
        [
          'the',
          'quick',
          'brown',
          'fox',
          'jumps',
          'over',
          'lazy',
          'dog',
          'and',
          'runs',
          'through',
          'the',
          'silent',
          'forest',
          'where',
          'every',
          'shadow',
          'hides',
          'another',
          'story',
          'about',
          'people',
          'who',
          'learned',
          'to',
          'focus',
          'their',
          'minds',
          'while',
          'their',
          'fingers',
          'practiced',
          'the',
          'simple',
          'music',
          'of',
          'words',
        ],
        180,
      ),
    ],
  },
];

export const LESSONS: Lesson[] = [
  ...buildUnit('Home Row', homeRow, 1),
  ...buildUnit('Top Row', topRow, 1),
  ...buildUnit('Bottom Row', bottomRow, 1),
  ...buildUnit('Shift & Capitals', shifts, 1),
  ...buildUnit('Numbers', numbers, 1),
  ...buildUnit('Symbols', symbols, 1),
  ...buildUnit('Speed Building', speed, 1),
];

// Cross-unit prerequisites: first lesson of each unit requires the last lesson of the previous unit.
(function linkUnits() {
  const byUnit = new Map<string, Lesson[]>();
  for (const lesson of LESSONS) {
    const list = byUnit.get(lesson.unit) ?? [];
    list.push(lesson);
    byUnit.set(lesson.unit, list);
  }
  const unitOrder = [
    'Home Row',
    'Top Row',
    'Bottom Row',
    'Shift & Capitals',
    'Numbers',
    'Symbols',
    'Speed Building',
  ];
  for (let i = 1; i < unitOrder.length; i += 1) {
    const prevUnit = byUnit.get(unitOrder[i - 1]);
    const currUnit = byUnit.get(unitOrder[i]);
    if (prevUnit && currUnit && prevUnit.length > 0 && currUnit.length > 0) {
      currUnit[0].unlockRequires = prevUnit[prevUnit.length - 1].id;
    }
  }
})();

export function getLesson(id: string): Lesson | undefined {
  return LESSONS.find((lesson) => lesson.id === id);
}

export function isLessonUnlocked(
  lesson: Lesson,
  progress: Record<string, { completed: boolean }>,
): boolean {
  if (!lesson.unlockRequires) {
    return true;
  }
  return Boolean(progress[lesson.unlockRequires]?.completed);
}
